runtime: java
env: flex

# This sample incurs costs to run on the App Engine flexible environment. 
# The settings below are to reduce costs during testing and are not appropriate
# for production use. For more information, see:
# https://cloud.google.com/appengine/docs/flexible/python/configuring-your-app-with-app-yaml


steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
- name: 'gcr.io/cloud-builders/mvn'
  args: ['package']
skip_files:
- ^(.*/)?\.txt$
runtime_config:
   jdk: openjdk8
   server: jetty9
network:
  forwarded_ports:
    - 2222
manual_scaling:
  instances: 1
resources:
  cpu: 2
  memory_gb: 2.0
  disk_size_gb: 10